### ISSUE TITLE
D2 scavenged diode

### ISSUE THREAD

**Issue by Reddog176** [Real-Time-Kodi/Vindicktning#1]
What is the value of the d2 scavenged diode? I couldn't find polarity markings on the board, nor on your photos. So I need to replace the diode.

**Comment by Real-Time-Kodi** [comment]
D1 can be any general purpose diode. if you plug in the fan, make note of the positive red wire and place the anode facing the red wire and the cathode facing the black wire.

you should be able to test the polarity of the scavenged diode with a multimeter
